### ISSUE TITLE
Check Status Method 

### ISSUE THREAD

**Issue by beeeku** [MSG91/sendotp-node#10]
If you could provide checkStatus method that was available previously on this sdk , that would be very helpful .

**Comment by rwalkover** [comment]
Hello Beeeku, Thanks for writing, We know checkStatus can save your one SMS only but if you verify mobile again this will help you to improve the trust of your client that in the case of mobile number owner is change or someone try unethical action than you application should resend SMS and verify the number again.

**Comment by beeeku** [comment]
Previously We were using [https://sendotp.msg91.com/api/checkStatus](https://sendotp.msg91.com/api/checkStatus)  and according to that we verified the otp from client side and checkStatus of the mobile verification from the API side . So it would be helpful if you can provide that .
