### ISSUE TITLE
Can not set expiry time for otp

### ISSUE THREAD

**Issue by go4taj** [MSG91/sendotp-node#11]
setting expiry time for otp is not supported yet. can you please provide that.

**Comment by caype** [comment]
+1. 
Even though the documentation explains about the OTP expiry time feature, it throws an error when implemented.

**Comment by rwalkover** [comment]
Hello, @go4taj, @caype: OTP expiry added.
You just need to call this way:
sendOtp.setOtpExpiry('90'); //in minutes
