### ISSUE TITLE
Please Update Mocha Version According Node Security platform

### ISSUE THREAD

**Issue by beeeku** [MSG91/sendotp-node#15]
Hi According Node Security You should update your mocha package to avoid few known security issues .
![nsp](https://user-images.githubusercontent.com/2242358/30499625-eee1bb9a-9a78-11e7-9972-489af30f9c9c.png)

Thank you

**Comment by beeeku** [comment]
@rwalkover if you want I can send a pull request

**Comment by rwalkover** [comment]
@beeeku It would be great. 
Also, I suggest you join Dev Community of MSG91 i.e.  https://msg91.com/community/

**Comment by beeeku** [comment]
@rwalkover Done
