### ISSUE TITLE
otp sending failed still get success response

### ISSUE THREAD

**Issue by reshma-r-p** [MSG91/sendotp-node#17]
i have tried sendOtp.send for sending otp. 
And i got the response  
{ message: '376941717932393732393030', type: 'success' }
But when i checked it in MSG91 it shows the status as "Rejected by Kannel or Provider "

**Comment by rwalkover** [comment]
Hi, Reshma,
For better assistance please contact MSG91 Support at support@msg91.com

**Comment by ip-amity-tarun** [comment]
I am also facing a similar issue with the flow api?
