### ISSUE TITLE
Not able to use it in Nuxt.js Framework

### ISSUE THREAD

**Issue by kamleshkatpara** [MSG91/sendotp-node#21]
Hi,

I tried to install and use your package called sendotp : https://www.npmjs.com/package/sendotp

I have created a plugin 'sendotp' in my plugins directory here's the code:

import Vue from 'vue'
import SendOtp from 'sendotp';
const sendOtp = new SendOtp('AuthKey');
Vue.config.productionTip = false
Vue.use(SendOtp, sendOtp)

And added in my plugins list in nuxt.config.js:

plugins: ['~/plugins/sendotp.js']

And getting this error:

TypeError
Class constructor SendOtp cannot be invoked without 'new'

Any Suggestions ?

**Comment by sarfarazansari** [comment]
Check for this line`Vue.use(SendOtp, sendOtp)`

`SendOtp` is an constructor method. you have to use `new` keyword
